---
- name: Handle Nebula IP assignment
  include_tasks: ip_assignment.yml

- name: Nebula Install
  block:
    - name: Uninstall Nebula (clean install)
      include_tasks: uninstall.yml
      when: nebula_clean_install|bool

    - name: Preflight checks
      include_tasks: preflight.yml

    - name: Install Nebula on all hosts 
      include_tasks: nebula.yml
    
    - name: Deploy Lighthouse
      include_tasks: lighthouse.yml
      when: inventory_hostname in groups['nebula_lighthouse']
    
    - name: Deploy Nebula Node
      include_tasks: node.yml
      when: inventory_hostname not in groups['nebula_lighthouse']

- name: Configure Cloudflare DNS for Nebula hosts
  include_tasks: cloudflare_dns.yml
  when: nebula_cloudflare_integration|bool
  tags:
    - nebula_dns
    - nebula_cloudflare
