- name: Sign certificate on lighthouse and fetch cert/key/CA
  include_tasks: sign.yml

- name: Ensure node has hosts file entry for lighthouse
  lineinfile:
    path: /etc/hosts
    line: "{{ nebula_lighthouse_internal_ip_addr }} {{ nebula_lighthouse_hostname }}.neb"
  when: nebula_node_lighthouse_in_hosts_file

- name: Ensure Cert, Key, CA files exist
  copy:
    dest: "{{ nebula_config_dir }}/{{ item['item'] }}"
    content: "{{ item['content'] | b64decode }}"
    owner: root
    group: root
    mode: 0600
  loop: "{{ lighthouse_files.results }}"
  loop_control:
    label: "{{ item['item'] }}"
  notify: restart nebula

- name: Ensure Nebula is configured
  template:
    src: node_config.yml.j2 
    dest: "{{ nebula_config_dir }}/config.yml"
    owner: root
    group: root
    mode: '0400'
  notify: restart nebula

- name: Ensure Nebula service exists
  template:
    src: node.service.j2
    dest: /etc/systemd/system/nebula.service
    owner: root
    group: root
    mode: '0644'

- name: Ensure Nebula service is enabled and running
  systemd: 
    name: nebula
    daemon_reload: yes
    enabled: yes
    masked: no
    state: started

- name: Ensure nebula-check is present
  template:
    src: nebula-check.sh.j2
    dest: "{{ nebula_config_dir }}/nebula-check.sh"
    owner: root
    group: root
    mode: '0755'
  when: nebula_install_check_cron|bool

- name: Ensure nebula-check is scheduled via cron
  cron:
    name: "nebula-check"
    minute: "{{ nebula_check_cron_minute | default('*/5') }}"
    job: "{{ nebula_config_dir }}/nebula-check.sh"
  when: nebula_install_check_cron|bool

